//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjeect
{
    using System;
    using System.Collections.Generic;
    
    public partial class do_obejrzenia
    {
        public int id_serialu { get; set; }
        public string nazwa { get; set; }
        public int rok_rozpoczecia { get; set; }
        public Nullable<int> rok_zakonczenia { get; set; }
        public Nullable<int> id_gatunku_1 { get; set; }
        public Nullable<int> id_gatunku_2 { get; set; }
        public Nullable<int> id_gatunku_3 { get; set; }
        public Nullable<int> id_stacji { get; set; }
        public int ilosc_sezonow { get; set; }
        public int ilosc_odcinkow { get; set; }
        public Nullable<int> czas_trwania_odcinka { get; set; }
    
        public virtual gatunki gatunki { get; set; }
        public virtual gatunki gatunki1 { get; set; }
        public virtual gatunki gatunki2 { get; set; }
        public virtual stacje_tv stacje_tv { get; set; }
    }
}
