//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class seriale_dbEntities : DbContext
    {
        public seriale_dbEntities()
            : base("name=seriale_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<do_obejrzenia> do_obejrzenia { get; set; }
        public virtual DbSet<gatunki> gatunki { get; set; }
        public virtual DbSet<koniec> koniec { get; set; }
        public virtual DbSet<na_biezaco> na_biezaco { get; set; }
        public virtual DbSet<nie_skonczone> nie_skonczone { get; set; }
        public virtual DbSet<przerwa> przerwa { get; set; }
        public virtual DbSet<seriale> seriale { get; set; }
        public virtual DbSet<stacje_tv> stacje_tv { get; set; }
    }
}
