//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjeect
{
    using System;
    using System.Collections.Generic;
    
    public partial class seriale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public seriale()
        {
            this.koniec = new HashSet<koniec>();
            this.na_biezaco = new HashSet<na_biezaco>();
            this.nie_skonczone = new HashSet<nie_skonczone>();
            this.przerwa = new HashSet<przerwa>();
        }
    
        public int id_serialu { get; set; }
        public string nazwa { get; set; }
        public int rok_rozpoczecia { get; set; }
        public Nullable<int> rok_zakonczenia { get; set; }
        public Nullable<int> id_gatunku_1 { get; set; }
        public Nullable<int> id_gatunku_2 { get; set; }
        public Nullable<int> id_gatunku_3 { get; set; }
        public Nullable<int> id_stacji { get; set; }
        public int ilosc_sezonow { get; set; }
        public int ilosc_odcinkow { get; set; }
        public Nullable<int> czas_trwania_odcinka { get; set; }
    
        public virtual gatunki gatunki { get; set; }
        public virtual gatunki gatunki1 { get; set; }
        public virtual gatunki gatunki2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<koniec> koniec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<na_biezaco> na_biezaco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nie_skonczone> nie_skonczone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<przerwa> przerwa { get; set; }
        public virtual stacje_tv stacje_tv { get; set; }
    }
}
